config/routes.rb
LifebuoySchool::Application.routes.draw do
  devise_for :users, ActiveAdmin::Devise.config
  root to: "admin/schools#index"
  ActiveAdmin.routes(self)
  resources :users_admin, :controller => 'users'
  resources :visits do
    member do
      put 'approve'
    end
  end
  resources :schools do
    member do
      get 'visits'
    end
    collection do
      get 'districts'
      get 'thanas'
    end
  end

end

app/models/visit.rb
class Visit < ActiveRecord::Base
  belongs_to :school
  belongs_to :user, foreign_key: :created_by
  has_many :images
  has_many :students_images
  has_many :acknowledgement_certificates
  validates :visited_at, :presence => true

  QUARTER = ['Q1 (JAN-MAR)', 'Q2 (APR-JUN)', 'Q3 (JULY-SEP)', 'Q4 (OCT-DEC)']

  scope :approved, -> { where(approve: true) }

  accepts_nested_attributes_for :images, allow_destroy: true
  accepts_nested_attributes_for :students_images, allow_destroy: true
  accepts_nested_attributes_for :acknowledgement_certificates, allow_destroy: true


end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_visit, only: [:show, :edit, :update, :approve, :destroy]

  # GET /visits
  # GET /visits.json
  def index
    @visits = Visit.all
  end

  # GET /visits/1
  # GET /visits/1.json
  def show
  end

  # GET /visits/new
  def new
    @visit = Visit.new(school_id: params[:school_id]||nil)
  end

  # GET /visits/1/edit
  def edit
  end

  # POST /visits
  # POST /visits.json
  def create
    @visit = Visit.new(visit_params)

    respond_to do |format|
      if @visit.save
        format.html { redirect_to @visit, notice: 'Visit was successfully created.' }
        format.json { render action: 'show', status: :created, location: @visit }
      else
        format.html { render action: 'new' }
        format.json { render json: @visit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /visits/1
  # PATCH/PUT /visits/1.json
  def update
    respond_to do |format|
      if @visit.update(visit_params)
        format.html { redirect_to @visit, notice: 'Visit was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @visit.errors, status: :unprocessable_entity }
      end
    end
  end

  def approve
    respond_to do |format|
      if @visit.update_attributes!(approve: true)
        format.html { redirect_to visits_url, notice: 'Visit was successfully approved.' }
      else
        format.html { redirect_to visits_url, notice: 'Visit was not approved.' }
      end
    end
  end

  # DELETE /visits/1
  # DELETE /visits/1.json
  def destroy
    @visit.destroy
    respond_to do |format|
      format.html { redirect_to visits_url }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_visit
    @visit = Visit.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def visit_params
    params.require(:visit).permit(:school_id, :agency_id, :quarter, :visited_at, :created_by, :approve)
  end
end

app/helpers/visits_helper.rb
module VisitsHelper
end

app/views/visits/_form.html.erb
<%= simple_form_for(@visit, html: {class: 'col-md-6'}) do |f| %>
    <%= f.error_notification %>

    <div class="form-inputs">
      <%= f.input :school_id, collection: School.all.collect { |c| [c.title, c.id] }, prompt: 'Please select School' %>
      <%= f.input :agency_id, collection: Agency.all.collect { |c| [c.name, c.id] }, prompt: 'Please select Agency' %>
      <%= f.input :quarter, collection: Visit::QUARTER, prompt: 'Please select Quarter' %>
      <%= f.label :visited_at, required: true %>
      <div id="start-date-timepicker" class="input-group date">
        <%= f.text_field :visited_at, :class => "form-control" %>
        <span class="input-group-addon add-on"><i class="glyphicon glyphicon-calendar"></i></span>
      </div>
      <%= f.hidden_field :created_by, value: current_user.id %>
      <br>
    </div>

    <div class="form-actions">
      <%= f.button :submit %>
    </div>
<% end %>

<script type="text/javascript">
    $(function () {
        $('#visit_visited_at').datetimepicker({format: "YYYY-MM-DD hh:mm:ss", useSeconds: true});
    });
</script>

app/views/visits/edit.html.erb
<h1>Editing visit</h1>

<%= render 'form' %>

app/views/visits/index.html.erb
<div class="row">
  <div class="col-lg-12">

    <h1>Listing visits</h1>

    <div class="table-responsive">
      <table class="table table-bordered table-hover data-table">
        <thead>
        <tr>
          <th>Quarter</th>
          <th>Visited at</th>
          <th>School</th>
          <th>Created by</th>
          <th>Status</th>
          <th></th>
          <th></th>
        </tr>
        </thead>

        <tbody>
        <% @visits.each do |visit| %>
            <tr>
              <td><%= visit.quarter %></td>
              <td><%= visit.visited_at %></td>
              <td><%= link_to visit.school.title, visit.school, :class => 'text-info', :target => '_blank' %></td>
              <td><%= visit.user.try(:name) %></td>
              <td>
                <% if visit.approve? %>
                    <%= link_to "Approved", "#", :class => "btn btn-xs btn-default" %>
                <% else %>
                    <% if current_user.admin? %>
                        <%= link_to "Pending", approve_visit_path(visit), method: :put, :class => "btn btn-xs btn-info" %>
                    <% else %>
                        <%= link_to "Pending", "#", :class => "btn btn-xs btn-info" %>
                    <% end %>
                <% end %>
              </td>
              <td><%= link_to 'Edit', edit_visit_path(visit) %></td>
              <td><%= link_to 'Destroy', visit, method: :delete, data: {confirm: 'Are you sure?'} %></td>
            </tr>
        <% end %>
        </tbody>
      </table>
    </div>
    <%= link_to 'New Visit', new_visit_path, :class => "btn btn-sm btn-primary" %>
  </div>
</div>

app/views/visits/new.html.erb
<h1>New visit</h1>

<%= render 'form' %>

app/views/visits/show.html.erb
<p>
  <strong>Quarter:</strong>
  <%= @visit.quarter %>
</p>

<p>
  <strong>Visited at:</strong>
  <%= @visit.visited_at %>
</p>

<p>
  <strong>Created by:</strong>
  <%= @visit.created_by %>
</p>

<%= link_to 'Edit', edit_visit_path(@visit) %> |
<%= link_to 'Back', visits_path %>