config/routes.rb
LifebuoySchool::Application.routes.draw do
  devise_for :users, ActiveAdmin::Devise.config
  root to: "admin/schools#index"
  ActiveAdmin.routes(self)
  resources :users_admin, :controller => 'users'
  resources :visits do
    member do
      put 'approve'
    end
  end
  resources :schools do
    member do
      get 'visits'
    end
    collection do
      get 'districts'
      get 'thanas'
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable
  belongs_to :agency
  validates :first_name, :last_name, :title, :roles, :agency_id, :presence => true

  scope :with_role, lambda { |role| {:conditions => "roles_mask & #{2**ROLES.index(role.to_s)} > 0"} }
  scope :by_agency, ->(agency_id) { where(agency_id: agency_id) }

  ROLES = %w[admin agency_admin operator viewer ]
  ADMIN_ROLES = %w[admin agency_admin viewer]
  AGENCY_ADMIN_ROLES = %w[agency_admin operator]

  def roles=(roles)
    self.roles_mask = (roles & ROLES).map { |r| 2**ROLES.index(r) }.sum
  end

  def roles
    ROLES.reject { |r| ((roles_mask || 0) & 2**ROLES.index(r)).zero? }
  end

  def role?(role)
    roles.include? role.to_s
  end

  def admin?
    role?(:admin)
  end

  def agency_admin?
    role?(:agency_admin)
  end

  def operator?
    role?(:operator)
  end

  def viewer?
    role?(:viewer)
  end

  def name
    [self.first_name, self.last_name].join(" ")
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new()
  end

  def edit
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to users_admin_path(@user), notice: 'User was successfully created.' }
      else
        flash.now[:error] = @user.errors.full_messages
        format.html { render action: 'new' }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to users_admin_path(@user), notice: 'User was successfully updated.' }
      else
        flash.now[:error] = @user.errors.full_messages
        format.html { render action: 'edit' }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_admin_index_url }
    end
  end

  private
  def set_user
    @user = User.find(params[:id])
  end


  def user_params
    params.require(:user).permit(:first_name, :last_name, :title, :email, :password, :password_confirmation, {roles: []}, :roles_mask)
  end
end

app/views/users/_form.html.erb
<div class="row">
  <div class="col-lg-4">

    <%= form_for @user, url: @user.new_record? ? users_admin_index_path(@user) : users_admin_path(@user) do |f| %>
        <div class="form-group">
          <%= f.label :first_name, :class => "required" %>
          <%= f.text_field :first_name, :class => "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :last_name, :class => "required" %>
          <%= f.text_field :last_name, :class => "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :title %>
          <%= f.text_field :title, :class => "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :Permissions %>
          <br>
          <% User::ROLES.each do |role| %>
              <div class="row">
                <div class="col-md-4">
                  <% unless role.nil? %>
                      <%= check_box_tag "user[roles][]", role, @user.roles.include?(role), id: role %>
                      <%= h "#{role.try(:humanize)}" %>
                  <% end %>
                </div>
              </div>
              <br> <br>
          <% end %>
          <%= hidden_field_tag "user[roles][]", "" %>
        </div>

        <div class="form-group">
          <%= f.label :email, "Email Address", :class => "required" %>
          <%= f.text_field :email, :class => "form-control" %>
        </div>
        <% unless current_user.admin? && !@user.new_record? %>
            <div class="form-group">
              <%= f.label :password, :class => "required" %>
              <%= f.password_field :password, :class => "form-control" %>
            </div>
            <div class="form-group">
              <%= f.label :password_confirmation, "Confirm Password", :class => "required" %>
              <%= f.password_field :password_confirmation, :class => "form-control" %>
            </div>
        <% end %>
        <div class="form-actions">
          <%= f.submit %>
        </div>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', users_admin_path(@user) %> |
<%= link_to 'Back', users_admin_path %>

app/views/users/index.html.erb
<div class="row">
  <div class="col-lg-12">
    <h2>Users</h2>

    <div class="table-responsive">
      <table class="table table-bordered table-hover data-table">
        <thead>
        <tr>
          <th>Name</th>
          <th>Title</th>
          <th>Permission</th>
          <th>Email</th>
          <th></th>
          <th></th>
          <th></th>
        </tr>
        </thead>

        <tbody>
        <% @users.each do |user| %>
            <tr>
              <td><%= user.name %></td>
              <td><%= user.title %></td>
              <td><%= user.roles %></td>
              <td><%= user.email %></td>
              <td><%= link_to 'Show', users_admin_path(user) %></td>
              <td><%= link_to 'Edit', edit_users_admin_path(user) %></td>
              <td><%= link_to 'Destroy', users_admin_path(user), method: :delete, data: {confirm: 'Are you sure?'} %></td>
            </tr>
        <% end %>
        </tbody>
      </table>
    </div>
    <%= link_to 'New User', new_users_admin_path, :class => "btn btn-sm btn-info" %>
  </div>
</div><!-- /.row -->

app/views/users/new.html.erb
<h1>Create New user</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<p>
  <strong>First Name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last Name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_users_admin_path(@user) %> |
<%= link_to 'Back', users_admin_path %>