config/routes.rb
LifebuoySchool::Application.routes.draw do
  devise_for :users, ActiveAdmin::Devise.config
  root to: "admin/schools#index"
  ActiveAdmin.routes(self)
  resources :users_admin, :controller => 'users'
  resources :visits do
    member do
      put 'approve'
    end
  end
  resources :schools do
    member do
      get 'visits'
    end
    collection do
      get 'districts'
      get 'thanas'
    end
  end

end

app/models/school.rb
class School < ActiveRecord::Base
  belongs_to :division
  belongs_to :district
  belongs_to :thana
  belongs_to :agency
  belongs_to :user, foreign_key: :created_by
  has_many :completion_certificates
  has_one :first_visit
  has_one :second_visit
  has_one :third_visit
  has_one :fourth_visit


  validates :year, :state, :division_id, :district_id, :thana_id, :union, :title, :headmaster_name, :boys, :girls,
            :agency_id, :quarter, :honorific, :mobile, :data_entry_operator, :presence => true

  validates :phone, :contact_number, numericality: true, allow_blank: true
  validates :boys, :girls, numericality: true
  validates :mobile, length: {minimum: 13, maximum: 14, message: 'Mobile Number should be 11 digits'}

  accepts_nested_attributes_for :first_visit
  accepts_nested_attributes_for :second_visit
  accepts_nested_attributes_for :third_visit
  accepts_nested_attributes_for :fourth_visit
  accepts_nested_attributes_for :completion_certificates, allow_destroy: true

  attr_accessor :remove_photo

  before_create :set_uniq_id

  scope :not_reviewed, -> { where(reviewed: false) }
  scope :not_draft, -> { where(draft: false) }
  scope :pending, -> { where(status: 'pending') }
  scope :admin_approved, -> { where(status: 'admin_approved') }
  scope :agency_approved, -> { where(status: 'agency_approved') }
  scope :approved, -> { where(status: ['agency_approved', 'admin_approved']) }
  scope :order_as_district, -> { order('district_id ASC') }
  scope :order_id_desc, -> { order('id DESC') }
  scope :by_agency, ->(agency_id) { where(agency_id: agency_id) }


  state_machine :status, :initial => :pending do
    event :agency_approve do
      transition :pending => :agency_approved
    end

    event :admin_approve do
      transition :agency_approved => :admin_approved
    end
  end

  def set_uniq_id
    number = loop do
      token = "UBL_#{self.agency.code}_#{self.thana.code}_#{rand(36**5).to_s(36)}"
      break token.upcase! unless School.exists?(unique_id: token)
    end
    self.unique_id = number
  end

  def total_students
    [boys.to_i, girls.to_i].sum
  end

  def created_by
    self.user.try(:name)
  end

  def headmaster
    [self.honorific, self.headmaster_name].join(" ")
  end

  def review!
    self.update_attributes(reviewed: true)
  end

  def agency_operator
    [self.data_entry_operator, self.agency.code].join("_")
  end

  def approved?
    self.status == "agency_approved" || self.status == "admin_approved"
  end

  def self.fetch_all(current_user, not_draft=false)

    if not_draft
      schools = School.not_draft
    else
      if current_user.admin?
        schools = School.agency_approved.not_reviewed
      elsif current_user.agency_admin?
        schools = School.by_agency(current_user.agency_id).not_draft
      elsif current_user.viewer?
        schools = School.admin_approved
      elsif current_user.operator?
        schools = School.by_agency(current_user.agency_id).load
      end
    end
    return {
        unique_id: schools.uniq_by(&:unique_id).count,
        division: schools.uniq_by(&:division).count,
        district: schools.uniq_by(&:district).count,
        thana: schools.uniq_by(&:thana).count,
        union: schools.uniq_by(&:union).count,
        title: schools.uniq_by(&:title).count,
        mobile: schools.uniq_by(&:mobile).count,
        boys: schools.sum(:boys),
        girls: schools.sum(:girls),
        total_student: schools.sum(:boys).to_i + schools.sum(:girls).to_i,
        back_checked: "Yes :: #{schools.where(back_checked: true).count} <br> No :: #{schools.where(back_checked: false).count}",
        spot_checked: "Yes :: #{schools.where(spot_checked: true).count} <br> No :: #{schools.where(spot_checked: false).count}"
    }
  end

end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_school, only: [:show, :edit, :update, :destroy]

  # GET /schools
  # GET /schools.json
  def index
    @schools = School.all
  end

  # GET /schools/1
  # GET /schools/1.json
  def show
    @visits = @school.visits.approved
  end

  # GET /schools/new
  def new
    @school = School.new
  end

  # GET /schools/1/edit
  def edit
  end

  # POST /schools
  # POST /schools.json
  def create
    @school = School.new(school_params)

    respond_to do |format|
      if @school.save
        format.html { redirect_to @school, notice: 'School was successfully created.' }
        format.json { render action: 'show', status: :created, location: @school }
      else
        format.html { render action: 'new' }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schools/1
  # PATCH/PUT /schools/1.json
  def update
    respond_to do |format|
      if @school.update(school_params)
        format.html { redirect_to @school, notice: 'School was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schools/1
  # DELETE /schools/1.json
  def destroy
    @school.destroy
    respond_to do |format|
      format.html { redirect_to schools_url }
      format.json { head :no_content }
    end
  end

  def districts
    if params[:division_id]
      division = Division.find(params[:division_id])
      @districts = division.districts
    else
      @districts = Division.all
    end
    render :json => @districts.collect { |district| {:id => district.id, :name => district.name} }
  end

  def thanas
    if params[:district_id]
      district = District.find(params[:district_id])
      @thanas = district.thanas
    else
      @thanas = District.all
    end
    render :json => @thanas.collect { |thana| {:id => thana.id, :name => thana.name} }
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_school
    @school = School.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def school_params
    params.require(:school).permit(:year, :unique_id, :state, :division_id, :district_id, :thana_id, :union, :title, :headmaster_name, :phone, :boys, :girls, :created_by)
  end
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/views/schools/_form.html.erb
<%= simple_form_for(@school, html: {class: 'col-md-6'}) do |f| %>
    <%= f.error_notification %>

    <div class="form-inputs">
      <%= f.input :year, collection: 2010..2050, prompt: "Please select Year", required: true %>
      <%= f.input :unique_id %>
      <%= f.input :state, :input_html => {:value => f.object.state || 'Bangladesh'}, label: "Country" %>
      <%= f.input :division_id, collection: Division.all.collect { |c| [c.name, c.id] }, prompt: 'Please select Division', required: true %>
      <%= f.input :district_id, collection: District.all.collect { |c| [c.name, c.id] }, prompt: 'Please select District', required: true %>
      <%= f.input :thana_id, collection: Thana.all.collect { |c| [c.name, c.id] }, prompt: 'Please select Thana', required: true %>
      <%= f.input :union, required: true %>
      <%= f.input :title, required: true %>
      <%= f.input :headmaster_name, required: true %>
      <%= f.input :phone, required: true %>
      <%= f.input :boys, required: true %>
      <%= f.input :girls, required: true %>
      <%= f.hidden_field :created_by, value: current_user.id %>
    </div>

    <div class="form-actions">
      <%= f.button :submit %>
    </div>
<% end %>

app/views/schools/edit.html.erb
<h1>Editing school</h1>

<%= render 'form' %>

app/views/schools/index.html.erb
<div class="row">
  <div class="col-lg-12">

    <h1>Listing schools</h1>

    <div class="table-responsive">
      <table class="table table-bordered table-hover data-table">
        <thead>
        <tr>
          <th>Year</th>
          <th>Unique</th>
          <th>Country</th>
          <th>Division</th>
          <th>District</th>
          <th>Thana</th>
          <th>Union</th>
          <th>Title</th>
          <th>Headmaster name</th>
          <th>Phone</th>
          <th>Boyes</th>
          <th>Girls</th>
          <th>Created by</th>
          <th></th>
          <th></th>
          <th></th>
        </tr>
        </thead>

        <tbody>
        <% @schools.each do |school| %>
            <tr>
              <td><%= school.year %></td>
              <td><%= school.unique_id %></td>
              <td><%= school.state %></td>
              <td><%= school.division.name %></td>
              <td><%= school.district.name %></td>
              <td><%= school.thana.name %></td>
              <td><%= school.union.name %></td>
              <td><%= link_to school.title, school, :class => 'text-info', :target => '_blank' %></td>
              <td><%= school.headmaster_name %></td>
              <td><%= school.phone %></td>
              <td><%= school.boys %></td>
              <td><%= school.girls %></td>
              <td><%= school.user.try(:name) %></td>
              <td><%= link_to 'Visit School', new_visit_path(school_id: school) %></td>
              <td><%= link_to 'Edit', edit_school_path(school) %></td>
              <td><%= link_to 'Destroy', school, method: :delete, data: {confirm: 'Are you sure?'} %></td>
            </tr>
        <% end %>
        </tbody>
      </table>
    </div>
    <%= link_to 'New School', new_school_path, :class => "btn btn-sm btn-primary" %>
  </div>
</div>

app/views/schools/new.html.erb
<h1>New school</h1>

<%= render 'form' %>

app/views/schools/show.html.erb
<div class="row">
  <div class="col-sm-6">
    <h3>School Details</h3>
    <ul class="list-group">
      <a href="#" class="list-group-item "><b>Year</b> <span class="pull-right"><%= @school.year %></span></a>
      <a href="#" class="list-group-item "><b>Unique</b> <span class="pull-right"><%= @school.unique_id %></span></a>
      <a href="#" class="list-group-item "><b>Country</b> <span class="pull-right"><%= @school.state %></span></a>
      <a href="#" class="list-group-item "><b>Division</b> <span class="pull-right"><%= @school.division.name %></span></a>
      <a href="#" class="list-group-item "><b>District</b> <span class="pull-right"><%= @school.district.name %></span></a>
      <a href="#" class="list-group-item "><b>Thana</b> <span class="pull-right"><%= @school.thana.name %></span></a>
      <a href="#" class="list-group-item "><b>Union</b> <span class="pull-right"><%= @school.union.name %></span></a>
      <a href="#" class="list-group-item "><b>Title</b> <span class="pull-right"><%= @school.title %></span></a>
      <a href="#" class="list-group-item "><b>Headmaster name</b> <span class="pull-right"><%= @school.headmaster_name %></span></a>
      <a href="#" class="list-group-item "><b>Phone</b> <span class="pull-right"><%= @school.phone %></span></a>
      <a href="#" class="list-group-item "><b>Boyes</b> <span class="pull-right"><%= @school.boys %></span></a>
      <a href="#" class="list-group-item "><b>Girls</b> <span class="pull-right"><%= @school.girls %></span></a>
      <a href="#" class="list-group-item "><b>Total Student</b> <span class="pull-right"><%= @school.total_students %></span></a>
      <a href="#" class="list-group-item "><b>Data Entry Operator</b> <span class="pull-right"><%= @school.user.try(:name) %></span></a>
    </ul>
  </div>
  <div class="col-sm-6">
    <h3>School Visiting Details</h3>
    <% @visits.each do |visit| %>
        <ul class="list-group">
          <a href="#" class="list-group-item "><b>Quarter</b> <span class="pull-right"><%= visit.quarter %></span></a>
          <a href="#" class="list-group-item "><b>Visited at</b> <span class="pull-right"><%= visit.visited_at %></span></a>
          <a href="#" class="list-group-item "><b>Data Entry Operator</b> <span class="pull-right"><%= visit.user.try(:name) %></span></a>
        </ul>
    <% end %>
  </div>
</div>

<%= link_to ' Edit ', edit_school_path(@school), :class => "btn btn-sm btn-primary" %>