config/routes.rb
LifebuoySchool::Application.routes.draw do
  devise_for :users, ActiveAdmin::Devise.config
  root to: "admin/schools#index"
  ActiveAdmin.routes(self)
  resources :users_admin, :controller => 'users'
  resources :visits do
    member do
      put 'approve'
    end
  end
  resources :schools do
    member do
      get 'visits'
    end
    collection do
      get 'districts'
      get 'thanas'
    end
  end

end

app/views/layouts/_user_navigation.html.erb
<% if current_user.present? %>
    <li class="dropdown user-dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        <i class="glyphicon glyphicon-user"></i> <%= current_user.email %>
        <b class="caret"></b>
      </a>
      <ul class="dropdown-menu">

        <li>
          <%= link_to edit_user_registration_path(current_user) do %>
              <i class="glyphicon glyphicon-user"></i> Profile
          <% end %>
        </li>
        <li>
          <%= link_to schools_path do %>
              <i class="glyphicon glyphicon-list"></i> Schools
          <% end %>
        </li>
        <li>
          <%= link_to new_school_path do %>
              <i class="glyphicon glyphicon-share-alt"></i> Add New School
          <% end %>
        </li>
        <li>
          <%= link_to visits_path do %>
              <i class="glyphicon glyphicon-list"></i> Visits
          <% end %>
        </li>
        <li>
          <%= link_to new_visit_path do %>
              <i class="glyphicon glyphicon-pencil"></i> Visit School
          <% end %>
        </li>
        <li>
          <%= link_to users_admin_index_path do %>
              <i class="glyphicon glyphicon-user"></i> Users
          <% end %>
        </li>

        <li>
          <%= link_to(destroy_user_session_path, :method => :delete) do %>
              <i class="glyphicon glyphicon-off"></i> Log Out
          <% end %>
        </li>
      </ul>
    </li>
<% else %>
    <li>
      <%= link_to user_session_path do %>
          <i class="glyphicon glyphicon-log-in"></i> Login
      <% end %>
    </li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>LifeBoySchool</title>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= yield :head %>
</head>
<body>
<div id="wrap">
  <nav class="navbar navbar-red navbar-fixed-top" role="navigation">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/"><img class="img-responsive" src="assets/logo.gif" width="55px;"></a>
    </div>

    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <ul class="nav navbar-nav navbar-right navbar-user">
        <%= render partial: 'layouts/user_navigation' %>
      </ul>
    </div>
  </nav>

  <div class="container">
    <%= bootstrap_flash %>
    <%= yield %>
  </div>
  <div id="push"></div>
</div>

<div id="footer">
  <div class="container">
    <p>© Company 2014</p>
  </div>
</div>
</body>
</html>